kind: pipeline
name: default
trigger:
  branch:
    - dev
    - staging
    - master
  event:
    - push

steps:
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
    sources: ./src

